refactor(examples): move application start error catch from main func…
delftswa2018/loopback-next pull request #2
Opened 2018-03-13 15:22 UTC by ChampiYann

…tion to main index

A similar refactoring as in the CLI generator template is applied to the examples to complete the
fix for issue #925

fix #925

## Checklist

- [ ] `npm test` passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [ ] Related API Documentation was updated
- [ ] Affected artifact templates in `packages/cli` were updated
- [ ] Affected example projects in `packages/example-*` were updated

2018-03-14 09:07 UTC, cblazo approved these changes
Great, now the examples also catch the error upon calling the main-function instead of inside the main-function.

2018-03-14 12:10 UTC, jwooning requested changes
Looks good, but the title of the PR is too long (should be a single line).

Furthermore, I checked against the main strongloop/loopback-next repository and they changed the `src/index.ts.ejs` file, it now also contains an `await app.boot();` line like in the getting-started example, we have to fix this for the eventual PR to the original repo.

2018-03-20 10:02 UTC, jwooning approved these changes

2018-03-20 10:26 UTC, ghost approved these changes

2018-03-20 10:27 UTC, merged